### ISSUE TITLE
IndexError: index 7 is out of bounds for axis 1 with size 7？

### ISSUE THREAD

**Issue by hhhhsmx** [shenglandu/PushBoundary#3]
![image](https://user-images.githubusercontent.com/93530021/225594844-3e945b97-3355-4361-9b73-44b219995bfa.png)
Can you help me answer my doubts?Thanks

**Comment by shenglandu** [comment]
> ![image](https://user-images.githubusercontent.com/93530021/225594844-3e945b97-3355-4361-9b73-44b219995bfa.png) Can you help me answer my doubts?Thanks


Hi,

It seems that the data (i.e., .npy files) you are trying to read doesn't have additional fields such as normal, directions, and boundaries. Are you using the data mentioned [here](https://github.com/shenglandu/PushBoundary#data-preparation)? If so, I think there shouldn't occur this error. Otherwise, I will check again if the data is good and come back to you.


Best Regards,
Shenglan

**Comment by hhhhsmx** [comment]
> 

Thanks for your reply. I tried again and found that I was indeed using the wrong dataset. It has now been resolved. Thank you again!Best wishes！

**Comment by shenglandu** [comment]
> > 
> 
> Thanks for your reply. I tried again and found that I was indeed using the wrong dataset. It has now been resolved. Thank you again!Best wishes！

No worries :) I will close this issue now.


Best Regards,
Shenglan
