### ISSUE TITLE
Visualization results

### ISSUE THREAD

**Issue by Wei-Wu233** [shenglandu/PushBoundary#4]
Thanks for your code!

I follow you steps to train and test KPConv using SensatUrban datasets. But in tester.py line 357, write_ply(test_name, [points, preds, bpreds, boundary_probs, dpreds],['x', 'y', 'z', 'preds', 'is_boundary_preds', 'is_boundary_probs', 'dx', 'dy', 'dz']) doesn't write the color in ply files, and in test folder I use the meshlab to visualize the results, which is much different from the results in the paper. So here's how to change the "write_ply" to get the results in the final ply file with different categories of color information?

**Comment by shenglandu** [comment]
> Thanks for your code!
> 
> I follow you steps to train and test KPConv using SensatUrban datasets. But in tester.py line 357, write_ply(test_name, [points, preds, bpreds, boundary_probs, dpreds],['x', 'y', 'z', 'preds', 'is_boundary_preds', 'is_boundary_probs', 'dx', 'dy', 'dz']) doesn't write the color in ply files, and in test folder I use the meshlab to visualize the results, which is much different from the results in the paper. So here's how to change the "write_ply" to get the results in the final ply file with different categories of color information?

Hi, thanks for your interest in our work. 

In the paper, I use easy3D for visualization, where each prediction label is visualized as a discrete color. More links are attached [here](https://github.com/shenglandu/PushBoundary#visualization). If you would like to directly visualize the colors, you can specify the "r" "g" "b" values according to the field "preds", and add them into the output ply files.


Best Regards,
Shenglan

**Comment by Wei-Wu233** [comment]
If I want to get the same color segmentation as Fig.5 in the paper, do I have to modify r,g,b according to "preds" as you said, or does the result obtained from test contain the color segmentation information, and I need to use easy3D to get the final segmentation result with color? 如果方便的话，我们可以通过微信(conda_install)沟通，感谢大佬！！！

**Comment by shenglandu** [comment]
> If I want to get the same color segmentation as Fig.5 in the paper, do I have to modify r,g,b according to "preds" as you said, or does the result obtained from test contain the color segmentation information, and I need to use easy3D to get the final segmentation result with color? 如果方便的话，我们可以通过微信(conda_install)沟通，感谢大佬！！！

Hi,

The test .ply file itself doesn't contain color information. Using either meshlab or easy3D, you might need to specify the color yourself. If you would like to get exactly the same colors as in our paper, I can provide my label-to-color setting as below:

label r g b
0 85 107 47
1 0 200 0
2 255 165 0
3 41 49 101
4 0 0 0
5 0 0 200
6 255 100 255
7 200 200 200
8 89 47 95
9 200 0 0
10 200 200 0
11 0 200 200
12 0 160 255

This setting roughly follows the color setting of the original SensatUrban paper. Hope it helps. :)


Best Regards,
Shenglan

**Comment by Wei-Wu233** [comment]
Thank you for your response, I have two more questions here.
The first one: the data you provided here are preprocessed, I want to do the test on our dataset, do I need to preprocess our ply file and put it in input_0.200_test and complete_ply folder respectively? Is this part of the preprocessing code open source? I see that the preprocessing here is the same as the preprocessing provided by kpconv for preprocessing the S3DIS dataset, but the Area_5 for S3DIS is labeled, and SensatUrban's test set is unlabeled, so I'm not sure how this part with the processing code is constructed?
Second: how to specify the "r" "g" "b" values according to the field "preds", and add them into the output ply files.
Thanks again for the reply!

**Comment by shenglandu** [comment]
> 

Hi,

Regarding the 1st question:
Yes, it's necessary to preprocess the training data so that the data has GT boundary values and GT directions. For the test data it's not necessary, since the network will learn to predict boundaries and directions itself. For S3DIS, Area5 has GT boundaries and GT directions because the GT semantic labels are available; For SensatUrban test area, however, it's not the case since we don't have GT semantic labels. 
Preprocessing code is not open-source. But it's very easy to generate GT boundaries and directions via local search. More preprocessing details can be found [here](https://github.com/shenglandu/PushBoundary/issues/2).
It's not necessary to pre-process both the complete point cloud and the subsampled point cloud. Once you have the pre-processed complete clouds ready, KP-conv will automatically subsample it according to your specified grid size (the size is not necessary to be 3cm, you can modify it according to your own data). Details about data subsampling can be found in the [code](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/S3DIS_boundary.py).

Regarding the 2nd question:
If you would like to have your .ply files containing colors, one way is to read the file, find the "preds" field for each point, and assign the corresponding "r" "g" "b" and add the colors to the pointwise data, then output the new .ply files. But of course, there are many more different ways to achieve the final visualization.


Best Regards,
Shenglan

**Comment by Wei-Wu233** [comment]
Thanks for you reply!

For 1st question, I would like to express that in your project, there are three folders in datasets, namely "complete_ply", "input_0.200_test" and "input_0.200_train". In the "input_0.200_test" folder, each ply file corresponds to four files, for example " birmingham_block_2.ply", "birmingham_block_2_coarse_KDTree.pkl", "birmingham_block_2_KDTree. _KDTree.pkl", "birmingham_block_2_proj.pkl". We have a ply file of our own, so the corresponding four files should also be generated during testing. I noticed that during the training of S3DIS in KPConv, Area_5 is used as a test set to generate these four classes, so I put our ply file into KPConv to generate these four classes, but due to the lack of class, this result "ValueError: no field of name class". Since you are using Sensat dataset, the test set, such as "birmingham_block_2.ply" does not have class itself, so I would like to ask you how to generate those four files when the original ply file lacks class, thank you very much!

For 2nd question, "preds" means classer or label, and I write some code to add colors to each point. Thanks for your tips!

**Comment by shenglandu** [comment]
> Thanks for you reply!
> 
> For 1st question, I would like to express that in your project, there are three folders in datasets, namely "complete_ply", "input_0.200_test" and "input_0.200_train". In the "input_0.200_test" folder, each ply file corresponds to four files, for example " birmingham_block_2.ply", "birmingham_block_2_coarse_KDTree.pkl", "birmingham_block_2_KDTree. _KDTree.pkl", "birmingham_block_2_proj.pkl". We have a ply file of our own, so the corresponding four files should also be generated during testing. I noticed that during the training of S3DIS in KPConv, Area_5 is used as a test set to generate these four classes, so I put our ply file into KPConv to generate these four classes, but due to the lack of class, this result "ValueError: no field of name class". Since you are using Sensat dataset, the test set, such as "birmingham_block_2.ply" does not have class itself, so I would like to ask you how to generate those four files when the original ply file lacks class, thank you very much!
> 
> For 2nd question, "preds" means classer or label, and I write some code to add colors to each point. Thanks for your tips!

Hi, I think this can be an error where the code tries to read "class" while in your data there is not "class". Can you show me a screenshot of your error, and in which .py script does the error pop up?

In processing SensatUrban data, the code is designed not to read "class" field from test data but rather initialize pseudo class labels (since there is no class in test data). See [here](https://github.com/shenglandu/PushBoundary/blob/main/KPConv_Backbone/datasets/SensatUrban_boundary.py#L355) for details. I guess this can be a possible reason for your error?

Best,
Shenglan

**Comment by Wei-Wu233** [comment]
Thanks for your reply,  I added the class to the ply file to preprocess and got the final result, thanks again!

**Comment by shenglandu** [comment]
> Thanks for your reply, I added the class to the ply file to preprocess and got the final result, thanks again!

No worries. :) I will close the issue now.
